// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyoyWtEMbVGgCj5bMnFlzkLTw_0YTCGhQ',
    appId: '1:626407070234:web:be031373a00656d012cfa3',
    messagingSenderId: '626407070234',
    projectId: 'myfinancetraker',
    authDomain: 'myfinancetraker.firebaseapp.com',
    storageBucket: 'myfinancetraker.firebasestorage.app',
    measurementId: 'G-F6N2K2P26E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0LVmKpbDRRMMZqgVj8LC3AHbRokltiGs',
    appId: '1:626407070234:android:2eab2fe86ff2f6fc12cfa3',
    messagingSenderId: '626407070234',
    projectId: 'myfinancetraker',
    storageBucket: 'myfinancetraker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB5b_H9C5bWMQzCN6lbj-i2EcpXE2yrYk',
    appId: '1:626407070234:ios:d8d9aaa68e7e307112cfa3',
    messagingSenderId: '626407070234',
    projectId: 'myfinancetraker',
    storageBucket: 'myfinancetraker.firebasestorage.app',
    iosBundleId: 'com.example.myfinancetraker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB5b_H9C5bWMQzCN6lbj-i2EcpXE2yrYk',
    appId: '1:626407070234:ios:d8d9aaa68e7e307112cfa3',
    messagingSenderId: '626407070234',
    projectId: 'myfinancetraker',
    storageBucket: 'myfinancetraker.firebasestorage.app',
    iosBundleId: 'com.example.myfinancetraker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyoyWtEMbVGgCj5bMnFlzkLTw_0YTCGhQ',
    appId: '1:626407070234:web:213775b00a227d5612cfa3',
    messagingSenderId: '626407070234',
    projectId: 'myfinancetraker',
    authDomain: 'myfinancetraker.firebaseapp.com',
    storageBucket: 'myfinancetraker.firebasestorage.app',
    measurementId: 'G-97M3DKSFSB',
  );
}
